### ISSUE TITLE
A short description of the bug

### ISSUE THREAD

**Issue by garettmd** [acryldata/datahub-helm#196]
**Describe the bug**
UnknownTopicOrPartitionException when running kafka-setup-job

**To Reproduce**
Install datahub using the helm chart along with the prerequisites chart. When running the `kafka-configs.sh` script, it fails with:

```
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: 
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
        at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:180)
        at kafka.admin.ConfigCommand$.getResourceConfig(ConfigCommand.scala:577)
        at kafka.admin.ConfigCommand$.alterConfig(ConfigCommand.scala:347)
        at kafka.admin.ConfigCommand$.processCommand(ConfigCommand.scala:327)
        at kafka.admin.ConfigCommand$.main(ConfigCommand.scala:98)
        at kafka.admin.ConfigCommand.main(ConfigCommand.scala)
Caused by: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: 
```
None of the topics created in the previous steps with `kafka-topics.sh` appear to fail, so I'm not exactly sure what this command isn't finding.

**Expected behavior**
The command should run successfully.

**Additional context**
I'm running this on GKE, Kubernetes v1.24.5.
Datahub chart version: 0.2.111
Prerequisites chart version: 0.0.10

**Comment by pedro93** [comment]
Hello @garettmd 

Is this still an issue for you? We have made several helm chart releases since, can you try out the latest to see if it works for you?

Thank you
